title: Mythili Kandula
logo: /assets/img/Mythili Photo.jpg
description: Engineering Leader passionate about building high performing engineering teams with accountable culture and developing great products with innovation.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
